-- 프로시저(PROCEDURE) : PL/SQL문을 저장하는 객체
-- 필요할 때마다 복잡한 구문을 다시 입력할 필요 없이 간단히 호출해서 실행 결과를 얻을 수 있음

/* 프로시저 표현식
CREATE OR REPLACE PROCEDURE 프로시저명
    (매개변수1 [IN|OUT|IN OUT] 데이터타입 [:=DEFAULT값],
    (매개변수2 [IN|OUT|IN OUT] 데이터타입 [:=DEFAULT값],
    ...)
IS
    선언부
BEGIN
    실행부
EXCEPTION
    예외처리부
END;
/

- 프로시저 실행
EXECUTE 프로시저명;
EXEC 프로시저명;
*/
select * from employee_copy2;

CREATE OR REPLACE PROCEDURE DEL_EMPLOYEE_COPY2
IS
BEGIN
    DELETE FROM EMPLOYEE_COPY2;
    COMMIT;
END;
/

EXECUTE DEL_EMPLOYEE_COPY2;

SELECT * FROM USER_SOURCE;

-- 매개변수 있는 프로시저 생성
-- 프로시저 DEL_EMP_ID에 사용자로부터 입력받은 사번이 일치하는 사원을
-- EMPLOYEE_COPY 테이블에서 삭제하는 쿼리 작성

CREATE OR REPLACE PROCEDURE DEL_EMP_ID(V_EMP_ID EMPLOYEE.EMP_ID%TYPE)
IS
BEGIN
    DELETE FROM EMPLOYEE_COPY
    WHERE EMP_ID =V_EMP_ID;
    COMMIT;
END;
/
EXEC DEL_EMP_ID('&ID');

SELECT * FROM EMPLOYEE_COPY;

--사용자가 입력한 사번으로 사원의 이름, 급여, 보너스 조회하는 프로시저 SELECT_EMP_ID 생성

CREATE OR REPLACE PROCEDURE SELECT_EMP_ID(V_EMP_ID EMPLOYEE.EMP_ID%TYPE)
IS
    V_EMP_NAME EMPLOYEE.EMP_NAME%TYPE;
    V_SALARY EMPLOYEE.SALARY%TYPE;
    V_BONUS EMPLOYEE.BONUS%TYPE;
BEGIN
    select emp_name,salary,NVL(bonus,0)
    into V_EMP_NAME,V_SALARY,V_BONUS
    from employee 
    where emp_id= V_EMP_ID;
    
    DBMS_OUTPUT.PUT_LINE(V_EMP_NAME);
    DBMS_OUTPUT.PUT_LINE(V_SALARY);
    DBMS_OUTPUT.PUT_LINE(V_BONUS);
END;
/
EXEC SELECT_EMP_ID('&ID');

SET SERVEROUTPUT ON;

--IN 매개변수 : 프로시저 내부에서 사용하는 변수
--OUT 매개변수 : 프로시저 외부에서 사용되는 변수

CREATE OR REPLACE PROCEDURE SELECT_EMP_ID(
    V_EMP_ID IN EMPLOYEE.EMP_ID%TYPE,
    V_EMP_NAME OUT EMPLOYEE.EMP_NAME%TYPE,
    V_SALARY OUT EMPLOYEE.SALARY%TYPE,
    V_BONUS OUT EMPLOYEE.BONUS%TYPE
)
IS
BEGIN
    SELECT EMP_NAME, SALARY, NVL(BONUS,0)
    INTO V_EMP_NAME, V_SALARY, V_BONUS
    FROM EMPLOYEE
    WHERE EMP_ID = V_EMP_ID;
END;
/

--바인드 변수 : SQL문장을 실행할 때 SQL에 사용 값을 전달할 수 있는 통로 역할
--실행할 때 조회 결과가 저장될 변수 지정
VARIABLE VAR_EMP_NAME VARCHAR2(300);
VAR VAR_SALARY NUMBER;
VAR VAR_BONUS NUMBER;

PRINT VAR_EMP_NAME;
PRINT VAR_SALARY;
PRINT VAR_BONUS;

EXEC SELECT_EMP_ID('&ID', :VAR_EMP_NAME, :VAR_SALARY, :VAR_BONUS);

SET AUTOPRINT ON;
--프로시저 실행 시 바로 PRINT

--FUNCTION : PL/SQL문을 저장하는 객체
--프로시저와 사용 용도가 비슷하지만 프로시저와 다르게 실행결과를 되돌려 받을 수 있음(RETURN)

/*
CREATE OR REPLACE FUNCTION 함수명(매개변수1 매개변수타입, ...)
RETURN 데이터타입
IS
    선언부
BEGIN
    실행부
    RETURN 반환값;
EXCEPTION
    예외처리부
END;
/
*/

-- 216번 사원의 이름 출력 (함수 명: SELECT216)
CREATE OR REPLACE FUNCTION SELECT216
RETURN EMPLOYEE.EMP_NAME%TYPE
IS
    NAME EMPLOYEE.EMP_NAME%TYPE;
BEGIN
    SELECT EMP_NAME INTO NAME
    FROM EMPLOYEE
    WHERE EMP_ID=216;
    
    RETURN NAME;
END;
/

VARIABLE NAME216 VARCHAR2(20);
EXEC :NAME216 := SELECT216;

--사번을 입력받아 해당 사원의 보너스가 포함된 연봉을 계산하고 리턴하는 함수 생성: BONUS_CALC

CREATE OR REPLACE FUNCTION BONUS_CALC(V_EMP_ID EMPLOYEE.EMP_ID%TYPE)
RETURN NUMBER
IS
    V_SALARY EMPLOYEE.SALARY%TYPE;
    V_BONUS EMPLOYEE.BONUS%TYPE;
    CALC_SAL NUMBER;
BEGIN
    SELECT SALARY,NVL(BONUS,0)
    INTO V_SALARY, V_BONUS
    FROM EMPLOYEE
    WHERE EMP_ID=V_EMP_ID;
    
    CALC_SAL := (V_SALARY+(V_SALARY*V_BONUS))*12;
    
    RETURN CALC_SAL;
END;
/

VAR VAR_CALC NUMBER;
EXEC :VAR_CALC :=BONUS_CALC('&ID');


SELECT EMP_ID, EMP_NAME, BONUS_CALC(EMP_ID)
FROM EMPLOYEE
WHERE BONUS_CALC(EMP_ID) > 50000000;




