--DDL(DATA DEFINITION LANGUAGE) : 데이터 정의어
--객체를 만들고(CREATE), 수정하고(ALTER), 삭제하는(DROP) 구문

--ALTER : 객체를 수정하는 구문
--컬럼 추가, 컬럼 수정, 컬럼 삭제, 제약조건 추가, 제약조건 삭제,
--테이블명 수정, 컬럼명 수정, 제약조건명 수정...

--컬럼 추가,수정,삭제
SELECT * FROM EMPLOYEE_COPY2;

ALTER TABLE EMPLOYEE_COPY2
ADD (EMP_NO VARCHAR2(20));

ALTER TABLE EMPLOYEE_COPY2
ADD(LNAME VARCHAR2(40) DEFAULT '한국');

INSERT INTO EMPLOYEE_COPY2
VALUES(999, '남나눔', 2000000,'인사관리부','대리','990111-1111111',DEFAULT);

INSERT INTO EMPLOYEE_COPY2(EMP_ID,EMP_NAME,SALARY,DEPT_TITLE,JOB_NAME,EMP_NO)
VALUES(888, '남나눔', 2000000,'인사관리부','대리','990111-1111111');

INSERT INTO EMPLOYEE_COPY2
VALUES(777, '남나눔', 2000000,'인사관리부','대리','990111-1111111','중국');

INSERT INTO EMPLOYEE_COPY2
VALUES(666, '남나눔', 2000000,'인사관리부','대리','990111-1111111',NULL);

DESC EMPLOYEE_COPY2;

ALTER TABLE EMPLOYEE_COPY2
MODIFY EMP_ID CHAR(3) -- 자료형 바꾸기
MODIFY EMP_NAME VARCHAR2(30) --크기 바꾸기
MODIFY DEPT_TITLE CHAR(40) --자료형, 크기 바꾸기
MODIFY LNAME DEFAULT '미국'; --DEFAULT 바꾸기

ALTER TABLE EMPLOYEE_COPY2
MODIFY DEPT_TITLE VARCHAR2(10);

ALTER TABLE EMPLOYEE_COPY2
DROP COLUMN DEPT_TITLE;

SELECT * FROM EMPLOYEE_COPY2;

ALTER TABLE EMPLOYEE_COPY2
DROP (JOB_NAME, EMP_NO, LNAME);

ALTER TABLE EMPLOYEE_COPY2
DROP (EMP_ID, EMP_NAME, SALARY);

ALTER TABLE EMPLOYEE_COPY2
DROP COLUMN EMP_ID;

ALTER TABLE EMPLOYEE_COPY2
DROP COLUMN SALARY;

ALTER TABLE EMPLOYEE_COPY2
DROP COLUMN EMP_NAME;

ROLLBACK;

ALTER TABLE USER_GRADE
DROP COLUMN GRADE_CODE CASCADE CONSTRAINTS;

--제약조건 추가/삭제
CREATE TABLE ALTER_GRADE(
    GRADE_CODE NUMBER,
    GRADE_NAME VARCHAR2(30)
);

ALTER TABLE ALTER_GRADE
ADD CONSTRAINT PK_AG_CODE PRIMARY KEY(GRADE_CODE);

ALTER TABLE ALTER_GRADE
MODIFY GRADE_NAME CONSTRAINT NN_AG_NAME NOT NULL;

CREATE TABLE ALTER_USER(
    USER_NO NUMBER,--PK
    USER_ID VARCHAR2(20), --UQ
    USER_PWD VARCHAR2(30), --NN
    USER_NAME VARCHAR2(30),--NN
    GENDER VARCHAR2(10),--CK
    PHONE VARCHAR2(30),
    EMAIL VARCHAR2(50),
    GRADE_CODE NUMBER--FK
);

ALTER TABLE ALTER_USER
ADD PRIMARY KEY(USER_NO)
ADD UNIQUE(USER_ID)
MODIFY USER_PWD NOT NULL
MODIFY USER_NAME NOT NULL
ADD CHECK(GENDER IN ('남','여'))
ADD FOREIGN KEY(GRADE_CODE) REFERENCES ALTER_GRADE(GRADE_CODE);

--EMPLOYEE테이블의 DEPT_CODE에 외래키 제약조건 추가
--참조 테이블은 DEPARTMENT, 참조 컬럼은 DEPT_ID
ALTER TABLE EMPLOYEE
ADD FOREIGN KEY(DEPT_CODE) REFERENCES DEPARTMENT(DEPT_ID);

--DEPARTMENT테이블의 LOCATION_ID에 외래키 제약조건 추가
--참조 테이블은 LOCATION, 참조 컬럼은 LOCAL_CODE
ALTER TABLE DEPARTMENT
ADD FOREIGN KEY(LPOCATION_ID) REFERENCES LOCATION;

ALTER TABLE ALTER_USER
DROP CONSTRAINT SYS_C007539;

ALTER TABLE ALTER_USER
DROP CONSTRAINT SYS_C007538
DROP CONSTRAINT SYS_C007540
MODIFY USER_PWD NULL;

ALTER TABLE ALTER_USER
RENAME CONSTRAINT SYS_C007536 TO NN_AU_NAME;

ALTER TABLE CONS_NAME
RENAME COLUMN TEST_DATA1 TO TEST1;

ALTER TABLE MEMBER
RENAME TO MEM;

--테이블 삭제 : DROP
DROP TABLE MEM;
DROP TABLE CONS_NAME CASCADE CONSTRAINTS;




